### ISSUE TITLE
Packaging Populations with metadata

### ISSUE THREAD

**Issue by Hazelfire** [silentcoder99/Hex-DLC#12]
I was thinking that it should be possible to package a Population up with information such as it's win reward, it's generation count and it's layer sizes as to allow better recovery of populations that run on different configurations.

Is this a good idea? I was thinking of doing it in xml, maybe with [this library](https://github.com/zeux/pugixml). Are there better things I could be doing?

**Comment by silentcoder99** [comment]
I think that would be very useful, as I think the main thing left to do would be to experiment with different parameters and algorithms, so not having to keep track of every config would be good. 

Also I'm thinking that since we don't really know what parameters work, and so far the bots that have been made aren't seeming to move away from splotching, I think being able to set a benchmark opponent (storm, etc.) would improve the learning process, as we can get an idea of effective parameters based on how fast generated bots can beat it (or even multiple bots of increasing difficulty), and once the bots can beat the benchmark, they already have an effective starting point to evolve from past the benchmark.

**Comment by Hazelfire** [comment]
If we implement a benchmark bot, would it be a good idea to include a JS interpreter to read bots? It wouldn't be that hard and i quite like coding them, but is that out of the scope of this project?

I'll look into packaging bots for you!

Also, are you ok with me directly committing to your repo or do you want a pull request model. To be completely honest, I would prefer that my code went through at least one person before being put in the main repo, so I would prefer pull requests.

**Comment by Hazelfire** [comment]
But then again, pull requests are more suited for people who do not commit many changes... So maybe I should just directly commit.
Yeah, I'll do that, it's simpler

**Comment by silentcoder99** [comment]
Yeah, if you think it would be easier than righting a bunch of new bots in c++, I think it would be faster to utilize the js bots already made.

**Comment by Hazelfire** [comment]
Awesome! I'm onto it!

**Comment by Hazelfire** [comment]
So far, you can use the "getState" command to get information about the current config as well as the population. I was wondering if it would be good to be able to load these states too?

Either way. I would love to have a go at the JS Interpreter

**Comment by silentcoder99** [comment]
I think loading states would be good, especially once we start experimenting with parameters more.

**Comment by Hazelfire** [comment]
Out of curiosity, have you built this variant of the application? Do I need to include more detailed compilation instructions?

**Comment by silentcoder99** [comment]
I haven't actually, I've been waiting for boost to extract. It doesn't seem too hard to understand, but I'll tell you how I go once I've had a try.
